COUNTRIES_DATA = [
    {"name": "Senegal", "region": "AFRICA"},
    {"name": "Mali", "region": "AFRICA"},
    {"name": "Costa de Marfil", "region": "AFRICA"},
    {"name": "Camerun", "region": "AFRICA"},
    {"name": "Ghana", "region": "AFRICA"},
    {"name": "Nigeria", "region": "AFRICA"},
    {"name": "Kenia", "region": "AFRICA"},
    {"name": "Marruecos", "region": "AFRICA"},
    {"name": "Tunez", "region": "AFRICA"},
    {"name": "Etiopia", "region": "AFRICA"},
    {"name": "Tanzania", "region": "AFRICA"},
    {"name": "Uganda", "region": "AFRICA"},
    {"name": "Congo", "region": "AFRICA"},
    {"name": "Burkina Faso", "region": "AFRICA"},
    {"name": "Gambia", "region": "AFRICA"},
    {"name": "Mexico", "region": "LATAM"},
    {"name": "Guatemala", "region": "LATAM"},
    {"name": "Honduras", "region": "LATAM"},
    {"name": "El Salvador", "region": "LATAM"},
    {"name": "Nicaragua", "region": "LATAM"},
    {"name": "Colombia", "region": "LATAM"},
    {"name": "Ecuador", "region": "LATAM"},
    {"name": "Peru", "region": "LATAM"},
    {"name": "Bolivia", "region": "LATAM"},
    {"name": "Paraguay", "region": "LATAM"},
    {"name": "Republica Dominicana", "region": "LATAM"},
    {"name": "Cuba", "region": "LATAM"},
    {"name": "Haiti", "region": "LATAM"},
    {"name": "Brasil", "region": "LATAM"},
    {"name": "Argentina", "region": "LATAM"},
]

DEFAULT_KPIS = [
    {"code": "CS", "label": "Capital Services", "unit": "trx"},
    {"code": "RIA", "label": "RIA", "unit": "units"},
    {"code": "MG", "label": "Money Gram", "unit": "units"},
    {"code": "CORNERS", "label": "Corners", "unit": "units"},
]
